[world]
name = "zkTT"
description = "Powered by Starknet and Dojo"
cover_uri = "file://assets/cover.png"
icon_uri = "file://assets/icon.png"
website = "https://zktable.top/"
seed = "zktt"

[world.socials]
x = "https://x.com/zktabletop"
github = "https://github.com/webisoftSoftware"

[namespace]
default = "zktt"

[env]
rpc_url = "http://localhost:5050/"
# Default account for katana with seed = 0
account_address = "0xb3ff441a68610b30fd5e2abbf3a1548eb6ba6f3559f2862bf2dc757e5828ca"
private_key = "0x2bbf4f9fd0bbb2e60b0316c1fe0b76cf7a4d0198bd493ced9b8df2a3a24d68a"
world_address = "0x51dbcbcd51381f97c593c4412cb33fa596b247cf2f36c6336e31ed8d4d6a311"