[package]
name = "zktt"
version = "0.1.0"
cairo-version = "=2.7.0"

[dependencies]
dojo = { git = "https://github.com/dojoengine/dojo", tag = "v1.0.0-alpha.16" }
origami_random = { git = "https://github.com/dojoengine/origami.git", tag = "v1.0.0-alpha.16"}

[[target.dojo]]
