[package]
name = "zktt"
version = "0.1.0"

[dependencies]
starknet = "2.7.0"
dojo = {git = "https://github.com/dojoengine/dojo.git"}
cartridge_vrf = {git = "https://github.com/cartridge-gg/vrf.git"}
origami_random = {git = "https://github.com/dojoengine/origami.git"}

openzeppelin_testing = { git = "https://github.com/OpenZeppelin/cairo-contracts.git", rev = "a13bae3" }
openzeppelin_utils = { git = "https://github.com/OpenZeppelin/cairo-contracts.git", rev = "a13bae3" }
openzeppelin_test_common = { git = "https://github.com/OpenZeppelin/cairo-contracts.git", rev = "a13bae3" }

[[target.dojo]]
