[world]
kind = "WorldContract"
class_hash = "0x6f4515274ee23404789c3351a77107d0ec07508530119822046600ca6948d6e"
original_class_hash = "0x6f4515274ee23404789c3351a77107d0ec07508530119822046600ca6948d6e"
abi = "manifests/dev/deployment/abis/dojo-world.json"
address = "0x51dbcbcd51381f97c593c4412cb33fa596b247cf2f36c6336e31ed8d4d6a311"
transaction_hash = "0x26fa0341a9e07ea8eaf2ef678678b3649a6af30189a46be9b812369d9120846"
block_number = 3
seed = "zktt"
manifest_name = "dojo-world"

[world.metadata]
profile_name = "dev"
rpc_url = "http://localhost:5050/"

[base]
kind = "Class"
class_hash = "0x2427dd10a58850ac9a5ca6ce04b7771b05330fd18f2e481831ad903b969e6b2"
original_class_hash = "0x2427dd10a58850ac9a5ca6ce04b7771b05330fd18f2e481831ad903b969e6b2"
abi = "manifests/dev/deployment/abis/dojo-base.json"
tag = "dojo-base"
manifest_name = "dojo-base"

[[contracts]]
kind = "DojoContract"
address = "0x1b2ba3a5ef3dad87800227153fa14e25191ff2a263702380ff25bdd5d538f9b"
class_hash = "0xc9b4c3ddbbc7bd63baaeeb1a9c4e4e8e0a58477ff7c12f6f9cdc8ced847d1a"
original_class_hash = "0xc9b4c3ddbbc7bd63baaeeb1a9c4e4e8e0a58477ff7c12f6f9cdc8ced847d1a"
base_class_hash = "0x2427dd10a58850ac9a5ca6ce04b7771b05330fd18f2e481831ad903b969e6b2"
abi = "manifests/dev/deployment/abis/contracts/zktt-game-28af44a4.json"
reads = []
writes = []
init_calldata = []
tag = "zktt-game"
systems = []
manifest_name = "zktt-game-28af44a4"

[[models]]
kind = "DojoModel"
class_hash = "0x3afde5ab167e536486f8b9baa82e4cdc9ba81cc9cb0911979f997c7bd16174b"
original_class_hash = "0x3afde5ab167e536486f8b9baa82e4cdc9ba81cc9cb0911979f997c7bd16174b"
abi = "manifests/dev/deployment/abis/models/zktt-ActionComponent-4b078bf5.json"
tag = "zktt-ActionComponent"
qualified_path = "zktt::models::action_component"
manifest_name = "zktt-ActionComponent-4b078bf5"

[[models.members]]
name = "ent_name"
type = "ByteArray"
key = true

[[models.members]]
name = "from"
type = "ContractAddress"
key = false

[[models.members]]
name = "to"
type = "ContractAddress"
key = false

[[models.members]]
name = "action_type"
type = "EnumActionType"
key = false

[[models.members]]
name = "card_value"
type = "u8"
key = false

[[models.members]]
name = "copies_left"
type = "u8"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x31757045fc3d7e1c85283d35ada3756c5c6ae7781a20fe8c0b73c9121a8b67f"
original_class_hash = "0x31757045fc3d7e1c85283d35ada3756c5c6ae7781a20fe8c0b73c9121a8b67f"
abi = "manifests/dev/deployment/abis/models/zktt-AssetComponent-1807332e.json"
tag = "zktt-AssetComponent"
qualified_path = "zktt::models::asset_component"
manifest_name = "zktt-AssetComponent-1807332e"

[[models.members]]
name = "ent_owner"
type = "ContractAddress"
key = true

[[models.members]]
name = "name"
type = "ByteArray"
key = false

[[models.members]]
name = "value"
type = "u8"
key = false

[[models.members]]
name = "copies_left"
type = "u8"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x7284de8373aa92d238ef9cb3b24a306f5e6b910099312c72b5be246671b0bd2"
original_class_hash = "0x7284de8373aa92d238ef9cb3b24a306f5e6b910099312c72b5be246671b0bd2"
abi = "manifests/dev/deployment/abis/models/zktt-AssetGroupComponent-249e0416.json"
tag = "zktt-AssetGroupComponent"
qualified_path = "zktt::models::asset_group_component"
manifest_name = "zktt-AssetGroupComponent-249e0416"

[[models.members]]
name = "ent_owner"
type = "ContractAddress"
key = true

[[models.members]]
name = "set"
type = "Array<BlockchainComponent>"
key = false

[[models.members]]
name = "total_fee_value"
type = "u8"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x220afd5882afe5c2409041d02424cdf1ce30b7f6dc63f34664b2cfb0f6ec86a"
original_class_hash = "0x220afd5882afe5c2409041d02424cdf1ce30b7f6dc63f34664b2cfb0f6ec86a"
abi = "manifests/dev/deployment/abis/models/zktt-BlockchainComponent-1045d9c2.json"
tag = "zktt-BlockchainComponent"
qualified_path = "zktt::models::blockchain_component"
manifest_name = "zktt-BlockchainComponent-1045d9c2"

[[models.members]]
name = "ent_owner"
type = "ContractAddress"
key = true

[[models.members]]
name = "name"
type = "ByteArray"
key = false

[[models.members]]
name = "bc_type"
type = "EnumBlockchainType"
key = false

[[models.members]]
name = "fee"
type = "u8"
key = false

[[models.members]]
name = "value"
type = "u8"
key = false

[[models.members]]
name = "copies_left"
type = "u8"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x72b988b5d21c16e5e7143b0447526ad6645dcb69a4f198fecc5d456c643af01"
original_class_hash = "0x72b988b5d21c16e5e7143b0447526ad6645dcb69a4f198fecc5d456c643af01"
abi = "manifests/dev/deployment/abis/models/zktt-CardComponent-3f69a520.json"
tag = "zktt-CardComponent"
qualified_path = "zktt::models::card_component"
manifest_name = "zktt-CardComponent-3f69a520"

[[models.members]]
name = "ent_owner"
type = "ContractAddress"
key = true

[[models.members]]
name = "category"
type = "EnumCardCategory"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x3b5de3caf8703194c3869b964723141ecb87034b3317d79ca59c3ed05273785"
original_class_hash = "0x3b5de3caf8703194c3869b964723141ecb87034b3317d79ca59c3ed05273785"
abi = "manifests/dev/deployment/abis/models/zktt-DealerComponent-43b3243f.json"
tag = "zktt-DealerComponent"
qualified_path = "zktt::models::dealer_component"
manifest_name = "zktt-DealerComponent-43b3243f"

[[models.members]]
name = "ent_owner"
type = "ContractAddress"
key = true

[[models.members]]
name = "cards"
type = "Array<CardComponent>"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x22f673d8da0ebeacfdd3e0b86a309b4b5951b79110c176f7836868a07b79099"
original_class_hash = "0x22f673d8da0ebeacfdd3e0b86a309b4b5951b79110c176f7836868a07b79099"
abi = "manifests/dev/deployment/abis/models/zktt-DeckComponent-77a73e2c.json"
tag = "zktt-DeckComponent"
qualified_path = "zktt::models::deck_component"
manifest_name = "zktt-DeckComponent-77a73e2c"

[[models.members]]
name = "ent_owner"
type = "ContractAddress"
key = true

[[models.members]]
name = "blockchains"
type = "Array<BlockchainComponent>"
key = false

[[models.members]]
name = "asset_groups"
type = "Array<AssetGroupComponent>"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x1fcb6d0bd002c800e312ad09fc65672833178f3a288473a3f92d3cc3d91dd12"
original_class_hash = "0x1fcb6d0bd002c800e312ad09fc65672833178f3a288473a3f92d3cc3d91dd12"
abi = "manifests/dev/deployment/abis/models/zktt-GameComponent-6275ef70.json"
tag = "zktt-GameComponent"
qualified_path = "zktt::models::game_component"
manifest_name = "zktt-GameComponent-6275ef70"

[[models.members]]
name = "seed"
type = "felt252"
key = true

[[models.members]]
name = "state"
type = "EnumGameState"
key = false

[[models.members]]
name = "players"
type = "Array<ContractAddress>"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x1a511ddf059c011c928f407a7afeca9635ebd4d4ae479577b793274dddc8dc"
original_class_hash = "0x1a511ddf059c011c928f407a7afeca9635ebd4d4ae479577b793274dddc8dc"
abi = "manifests/dev/deployment/abis/models/zktt-GasFeeComponent-383a8699.json"
tag = "zktt-GasFeeComponent"
qualified_path = "zktt::models::gas_fee_component"
manifest_name = "zktt-GasFeeComponent-383a8699"

[[models.members]]
name = "ent_owner"
type = "ContractAddress"
key = true

[[models.members]]
name = "name"
type = "ByteArray"
key = false

[[models.members]]
name = "players_affected"
type = "Array<ContractAddress>"
key = false

[[models.members]]
name = "asset_group"
type = "Array<BlockchainComponent>"
key = false

[[models.members]]
name = "first_blockchain_type_affected"
type = "EnumBlockchainType"
key = false

[[models.members]]
name = "second_blockchain_type_affected"
type = "Option<EnumBlockchainType>"
key = false

[[models.members]]
name = "fee_per_player"
type = "u8"
key = false

[[models.members]]
name = "value"
type = "u8"
key = false

[[models.members]]
name = "copies_left"
type = "u8"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x165f3dd64f2f77f5820803975df7594d184886c4d911f0b7ff9ad5268df9f29"
original_class_hash = "0x165f3dd64f2f77f5820803975df7594d184886c4d911f0b7ff9ad5268df9f29"
abi = "manifests/dev/deployment/abis/models/zktt-HandComponent-42d93026.json"
tag = "zktt-HandComponent"
qualified_path = "zktt::models::hand_component"
manifest_name = "zktt-HandComponent-42d93026"

[[models.members]]
name = "ent_owner"
type = "ContractAddress"
key = true

[[models.members]]
name = "cards"
type = "Array<CardComponent>"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x34ecae77519809517363cf71943000537035ed3ddd2f5e76c79d8d3df53b9bf"
original_class_hash = "0x34ecae77519809517363cf71943000537035ed3ddd2f5e76c79d8d3df53b9bf"
abi = "manifests/dev/deployment/abis/models/zktt-MajorityAttackComponent-2c122cea.json"
tag = "zktt-MajorityAttackComponent"
qualified_path = "zktt::models::majority_attack_component"
manifest_name = "zktt-MajorityAttackComponent-2c122cea"

[[models.members]]
name = "ent_owner"
type = "ContractAddress"
key = true

[[models.members]]
name = "name"
type = "ByteArray"
key = false

[[models.members]]
name = "value"
type = "u8"
key = false

[[models.members]]
name = "copies_left"
type = "u8"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x4efed27ac039030b9ed8b6c2fbfc7c28a51fb984ccf138c288bd77d23220896"
original_class_hash = "0x4efed27ac039030b9ed8b6c2fbfc7c28a51fb984ccf138c288bd77d23220896"
abi = "manifests/dev/deployment/abis/models/zktt-MoneyPileComponent-26e73eb7.json"
tag = "zktt-MoneyPileComponent"
qualified_path = "zktt::models::money_pile_component"
manifest_name = "zktt-MoneyPileComponent-26e73eb7"

[[models.members]]
name = "ent_owner"
type = "ContractAddress"
key = true

[[models.members]]
name = "cards"
type = "Array<AssetComponent>"
key = false

[[models.members]]
name = "total_value"
type = "u8"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x71c25f56882b82cc62410968e02d8a989ce1e9fba349c1b532aba2dd2544907"
original_class_hash = "0x71c25f56882b82cc62410968e02d8a989ce1e9fba349c1b532aba2dd2544907"
abi = "manifests/dev/deployment/abis/models/zktt-PlayerComponent-5fa6904e.json"
tag = "zktt-PlayerComponent"
qualified_path = "zktt::models::player_component"
manifest_name = "zktt-PlayerComponent-5fa6904e"

[[models.members]]
name = "ent_owner"
type = "ContractAddress"
key = true

[[models.members]]
name = "username"
type = "ByteArray"
key = false

[[models.members]]
name = "moves_remaining"
type = "u8"
key = false

[[models.members]]
name = "has_won"
type = "bool"
key = false

[[models.members]]
name = "score"
type = "u32"
key = false
